<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="idl" nsURI="idl" nsPrefix="idl">
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDLModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" eType="#//Service"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" upperBound="-1"
        eType="#//Structure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Containers" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
        eType="#//Exceptions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="const" upperBound="-1"
        eType="#//Const" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enum" upperBound="-1" eType="#//Enum"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedef" upperBound="-1"
        eType="#//TypeDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
        eType="#//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Containers">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="bool" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="byte" instanceClassName="java.lang.Byte"/>
  <eClassifiers xsi:type="ecore:EDataType" name="i16" instanceClassName="java.lang.Short"/>
  <eClassifiers xsi:type="ecore:EDataType" name="i32" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="long" instanceClassName="java.lang.Long"/>
  <eClassifiers xsi:type="ecore:EDataType" name="double" instanceClassName="java.lang.Double"/>
  <eClassifiers xsi:type="ecore:EDataType" name="string" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exceptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Const">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AcceptedType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="NewEnum2"/>
  <eClassifiers xsi:type="ecore:EClass" name="list">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Containers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="set">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Containers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Containers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldEnum" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enum" upperBound="-1" eType="#//Enum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldBool" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//bool"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldfunction" eType="#//FieldFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="byteArray" instanceClassName="oracle.dss.util.xdo.common.io.ByteArray"/>
  <eClassifiers xsi:type="ecore:EClass" name="Field" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldByte" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//byte"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldfunction" eType="#//FieldFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldByteArray" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" eType="#//byteArray"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldfunction" eType="#//FieldFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDouble" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//double"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldfunction" eType="#//FieldFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldI16" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//i16"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fifieldfunction" eType="#//FieldFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldI32" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//i32"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fifieldfunction" eType="#//FieldFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldLong" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//long"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldfunction" eType="#//FieldFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldString" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//string"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldstruct" eType="#//FieldStruct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldfunction" eType="#//FieldFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldStruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" lowerBound="1"
        upperBound="-1" eType="#//Structure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
        eType="#//Function"/>
  </eClassifiers>
</ecore:EPackage>
